queue_rules:
  - name: default
    conditions:
      # Conditions to get out of the queue (= merged)
      - check-success~=build \(2\.13\.\d+\)
      - check-success~=build \(3\.\d+\.\d+\)

pull_request_rules:
  - name: Label Scala Steward PRs
    conditions:
      - author=scala-steward
    actions:
      label:
        add: [dependencies, scala]

  - name: Merge dependency-update PRs
    conditions:
      - base=master
      - label=dependencies
      - check-success~=build \(2\.13\.\d+\)
      - check-success~=build \(3\.\d+\.\d+\)
    actions:
      queue:
        name: default
        method: squash


  - name: Merge PRs (rebase) which are ready to merge
    conditions:
      - label=ready-to-merge-rebase
      - base=master
      - check-success~=build \(2\.13\.\d+\)
      - check-success~=build \(3\.\d+\.\d+\)
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
    actions:
      queue:
        name: default
        method: rebase


  - name: Merge PRs (squash) which are ready to merge
    conditions:
      - label=ready-to-merge-squash
      - base=master
      - check-success~=build \(2\.13\.\d+\)
      - check-success~=build \(3\.\d+\.\d+\)
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
    actions:
      queue:
        name: default
        method: squash
