queue_rules:
  - name: Merge dependency-update PRs
    queue_conditions:
      - label=dependencies
      - base=master
    merge_conditions: []
    merge_method: squash

  - name: Merge PRs using label (rebase)
    queue_conditions:
      - label=ready-to-merge-rebase
      - base=master
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - "#review-threads-unresolved=0"
    merge_conditions: []
    merge_method: rebase

  - name: Merge PRs using label (squash)
    queue_conditions:
      - label=ready-to-merge-squash
      - base=master
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - "#review-threads-unresolved=0"
    merge_conditions: []
    merge_method: squash

pull_request_rules:
  - name: All PRs into queue
    conditions: []
    actions:
      queue:
