package outwatch

import org.scalajs.dom.raw.{ClipboardEvent, DragEvent, KeyboardEvent}
import org.scalajs.dom.MouseEvent
import rxscalajs.Observable
import outwatch.dom.helpers._

/**
  *
  */
package object dom {
  def div(args: VDomModifier*) = DomUtils.hyperscriptHelper("div")(args: _*)
  def span(args: VDomModifier*) = DomUtils.hyperscriptHelper("span")(args: _*)
  def h1(args: VDomModifier*) = DomUtils.hyperscriptHelper("h1")(args: _*)
  def button(args: VDomModifier*) = DomUtils.hyperscriptHelper("button")(args: _*)
  def a(args: VDomModifier*) = DomUtils.hyperscriptHelper("a")(args: _*)
  def label(args: VDomModifier*) = DomUtils.hyperscriptHelper("label")(args: _*)
  def input(args: VDomModifier*) = DomUtils.hyperscriptHelper("input")(args: _*)
  def hr(args: VDomModifier*) = DomUtils.hyperscriptHelper("hr")(args: _*)
  def ul(args: VDomModifier*) = DomUtils.hyperscriptHelper("ul")(args: _*)
  def abbr(args: VDomModifier*) = DomUtils.hyperscriptHelper("abbr")(args: _*)
  def address(args: VDomModifier*) = DomUtils.hyperscriptHelper("address")(args: _*)
  def area(args: VDomModifier*) = DomUtils.hyperscriptHelper("area")(args: _*)
  def article(args: VDomModifier*) = DomUtils.hyperscriptHelper("article")(args: _*)
  def aside(args: VDomModifier*) = DomUtils.hyperscriptHelper("aside")(args: _*)
  def audio(args: VDomModifier*) = DomUtils.hyperscriptHelper("audio")(args: _*)
  def b(args: VDomModifier*) = DomUtils.hyperscriptHelper("b")(args: _*)
  def base(args: VDomModifier*) = DomUtils.hyperscriptHelper("base")(args: _*)
  def bdi(args: VDomModifier*) = DomUtils.hyperscriptHelper("bdi")(args: _*)
  def blockquote(args: VDomModifier*) = DomUtils.hyperscriptHelper("blockquote")(args: _*)
  def br(args: VDomModifier*) = DomUtils.hyperscriptHelper("br")(args: _*)
  def li(args: VDomModifier*) = DomUtils.hyperscriptHelper("li")(args: _*)
  def bdo(args: VDomModifier*) = DomUtils.hyperscriptHelper("bdo")(args: _*)
  def canvas(args: VDomModifier*) = DomUtils.hyperscriptHelper("canvas")(args: _*)
  def caption(args: VDomModifier*) = DomUtils.hyperscriptHelper("caption")(args: _*)
  def cite(args: VDomModifier*) = DomUtils.hyperscriptHelper("cite")(args: _*)
  def code(args: VDomModifier*) = DomUtils.hyperscriptHelper("code")(args: _*)
  def col(args: VDomModifier*) = DomUtils.hyperscriptHelper("col")(args: _*)
  def colgroup(args: VDomModifier*) = DomUtils.hyperscriptHelper("colgroup")(args: _*)
  def datalist(args: VDomModifier*) = DomUtils.hyperscriptHelper("datalist")(args: _*)
  def dd(args: VDomModifier*) = DomUtils.hyperscriptHelper("dd")(args: _*)
  def del(args: VDomModifier*) = DomUtils.hyperscriptHelper("del")(args: _*)
  def details(args: VDomModifier*) = DomUtils.hyperscriptHelper("details")(args: _*)
  def dfn(args: VDomModifier*) = DomUtils.hyperscriptHelper("dfn")(args: _*)
  def dialog(args: VDomModifier*) = DomUtils.hyperscriptHelper("dialog")(args: _*)
  def dl(args: VDomModifier*) = DomUtils.hyperscriptHelper("dl")(args: _*)
  def dt(args: VDomModifier*) = DomUtils.hyperscriptHelper("dt")(args: _*)
  def em(args: VDomModifier*) = DomUtils.hyperscriptHelper("em")(args: _*)
  def embed(args: VDomModifier*) = DomUtils.hyperscriptHelper("embed")(args: _*)
  def fieldset(args: VDomModifier*) = DomUtils.hyperscriptHelper("fieldset")(args: _*)
  def figcaption(args: VDomModifier*) = DomUtils.hyperscriptHelper("figcaption")(args: _*)
  def figure(args: VDomModifier*) = DomUtils.hyperscriptHelper("figure")(args: _*)
  def footer(args: VDomModifier*) = DomUtils.hyperscriptHelper("footer")(args: _*)
  def form(args: VDomModifier*) = DomUtils.hyperscriptHelper("form")(args: _*)
  def header(args: VDomModifier*) = DomUtils.hyperscriptHelper("header")(args: _*)
  def h2(args: VDomModifier*) = DomUtils.hyperscriptHelper("h2")(args: _*)
  def h3(args: VDomModifier*) = DomUtils.hyperscriptHelper("h3")(args: _*)
  def h4(args: VDomModifier*) = DomUtils.hyperscriptHelper("h4")(args: _*)
  def h5(args: VDomModifier*) = DomUtils.hyperscriptHelper("h5")(args: _*)
  def h6(args: VDomModifier*) = DomUtils.hyperscriptHelper("h6")(args: _*)
  def i(args: VDomModifier*) = DomUtils.hyperscriptHelper("i")(args: _*)
  def iframe(args: VDomModifier*) = DomUtils.hyperscriptHelper("iframe")(args: _*)
  def img(args: VDomModifier*) = DomUtils.hyperscriptHelper("img")(args: _*)
  def ins(args: VDomModifier*) = DomUtils.hyperscriptHelper("ins")(args: _*)
  def keygen(args: VDomModifier*) = DomUtils.hyperscriptHelper("keygen")(args: _*)
  def legend(args: VDomModifier*) = DomUtils.hyperscriptHelper("legend")(args: _*)
  def main(args: VDomModifier*) = DomUtils.hyperscriptHelper("main")(args: _*)
  def mark(args: VDomModifier*) = DomUtils.hyperscriptHelper("mark")(args: _*)
  def menu(args: VDomModifier*) = DomUtils.hyperscriptHelper("menu")(args: _*)
  def menuitem(args: VDomModifier*) = DomUtils.hyperscriptHelper("menuitem")(args: _*)
  def meter(args: VDomModifier*) = DomUtils.hyperscriptHelper("meter")(args: _*)
  def nav(args: VDomModifier*) = DomUtils.hyperscriptHelper("nav")(args: _*)
  def ol(args: VDomModifier*) = DomUtils.hyperscriptHelper("ol")(args: _*)
  def optgroup(args: VDomModifier*) = DomUtils.hyperscriptHelper("optgroup")(args: _*)
  def option(args: VDomModifier*) = DomUtils.hyperscriptHelper("option")(args: _*)
  def output(args: VDomModifier*) = DomUtils.hyperscriptHelper("output")(args: _*)
  def p(args: VDomModifier*) = DomUtils.hyperscriptHelper("p")(args: _*)
  def param(args: VDomModifier*) = DomUtils.hyperscriptHelper("param")(args: _*)
  def pre(args: VDomModifier*) = DomUtils.hyperscriptHelper("pre")(args: _*)
  def progress(args: VDomModifier*) = DomUtils.hyperscriptHelper("progress")(args: _*)
  def section(args: VDomModifier*) = DomUtils.hyperscriptHelper("section")(args: _*)
  def select(args: VDomModifier*) = DomUtils.hyperscriptHelper("select")(args: _*)
  def small(args: VDomModifier*) = DomUtils.hyperscriptHelper("small")(args: _*)
  def strong(args: VDomModifier*) = DomUtils.hyperscriptHelper("strong")(args: _*)
  def sub(args: VDomModifier*) = DomUtils.hyperscriptHelper("sub")(args: _*)
  def summary(args: VDomModifier*) = DomUtils.hyperscriptHelper("summary")(args: _*)
  def sup(args: VDomModifier*) = DomUtils.hyperscriptHelper("sup")(args: _*)
  def table(args: VDomModifier*) = DomUtils.hyperscriptHelper("table")(args: _*)
  def tbody(args: VDomModifier*) = DomUtils.hyperscriptHelper("tbody")(args: _*)
  def td(args: VDomModifier*) = DomUtils.hyperscriptHelper("td")(args: _*)
  def textarea(args: VDomModifier*) = DomUtils.hyperscriptHelper("textarea")(args: _*)
  def tfoot(args: VDomModifier*) = DomUtils.hyperscriptHelper("tfoot")(args: _*)
  def th(args: VDomModifier*) = DomUtils.hyperscriptHelper("th")(args: _*)
  def thead(args: VDomModifier*) = DomUtils.hyperscriptHelper("thead")(args: _*)
  def time(args: VDomModifier*) = DomUtils.hyperscriptHelper("time")(args: _*)
  def tr(args: VDomModifier*) = DomUtils.hyperscriptHelper("tr")(args: _*)
  def track(args: VDomModifier*) = DomUtils.hyperscriptHelper("track")(args: _*)
  def video(args: VDomModifier*) = DomUtils.hyperscriptHelper("video")(args: _*)
  def wbr(args: VDomModifier*) = DomUtils.hyperscriptHelper("wbr")(args: _*)


  lazy val hidden = BoolAttributeBuilder("hidden")
  lazy val value = new AttributeBuilder[Any]("value")
  lazy val disabled = BoolAttributeBuilder("disabled")
  lazy val style = new AttributeBuilder[Any]("style")
  lazy val alt = new AttributeBuilder[String]("alt")
  lazy val href = new AttributeBuilder[String]("href")
  lazy val autocomplete = new AttributeBuilder[Any]("autocomplete")
  lazy val autofocus = new BoolAttributeBuilder("autofocus")
  lazy val autoplay = new BoolAttributeBuilder("autofocus")
  lazy val autosave = new AttributeBuilder[Any]("autosave")
  lazy val charset = new AttributeBuilder[Any]("charset")
  lazy val challenge = new AttributeBuilder[Any]("challenge")
  lazy val cols = new AttributeBuilder[Double]("cols")
  lazy val rows = new AttributeBuilder[Double]("rows")
  lazy val colspan = new AttributeBuilder[Any]("colspan")
  lazy val controls = new BoolAttributeBuilder("controls")
  lazy val contentEditable = new BoolAttributeBuilder("contenteditable")
  lazy val rowspan = new AttributeBuilder[Any]("rowspan")
  lazy val download = new AttributeBuilder[Any]("download")
  lazy val id = new AttributeBuilder[String]("id")
  lazy val max = new AttributeBuilder[Double]("max")
  lazy val maxLength = new AttributeBuilder[Int]("maxlength")
  lazy val min = new AttributeBuilder[Double]("min")
  lazy val minLength = new AttributeBuilder[Int]("minlength")
  lazy val media = new AttributeBuilder[Any]("media")
  lazy val method = new AttributeBuilder[Any]("method")
  lazy val muted = new BoolAttributeBuilder("muted")
  lazy val name = new AttributeBuilder[String]("name")
  lazy val novalidate = new BoolAttributeBuilder("novalidate")
  lazy val accept = new AttributeBuilder[Any]("accept")
  lazy val acceptCharset = new AttributeBuilder[Any]("accept-charset")
  lazy val action = new AttributeBuilder[Any]("action")
  lazy val align = new AttributeBuilder[Any]("align")
  lazy val src = new AttributeBuilder[Any]("src")
  lazy val srcset = new AttributeBuilder[Any]("srcset")
  lazy val checked = BoolAttributeBuilder("checked")
  lazy val coords = new AttributeBuilder[Any]("coords")
  lazy val data = new DynamicAttributeBuilder[Any](List("data"))
  lazy val list = new AttributeBuilder[Any]("list")
  lazy val multiple = new AttributeBuilder[Any]("multiple")
  lazy val datetime = new AttributeBuilder[Any]("datetime")
  lazy val default = new AttributeBuilder[Any]("default")
  lazy val dirname = new AttributeBuilder[Any]("dirname")
  lazy val draggable = new AttributeBuilder[Any]("draggable")
  lazy val dropzone = new AttributeBuilder[Any]("dropzone")
  lazy val enctype = new AttributeBuilder[Any]("enctype")
  lazy val formAction = new AttributeBuilder[Any]("formaction")
  lazy val headers = new AttributeBuilder[Any]("headers")
  lazy val high = new AttributeBuilder[Double]("high")
  lazy val low = new AttributeBuilder[Double]("low")
  lazy val icon = new AttributeBuilder[Any]("icon")
  lazy val integrity = new AttributeBuilder[Any]("integrity")
  lazy val isMap = new BoolAttributeBuilder("ismap")
  lazy val itemProp = new AttributeBuilder[Any]("itemprop")
  lazy val keyType = new AttributeBuilder[Any]("keytype")
  lazy val kind = new AttributeBuilder[Any]("kind")
  lazy val label = new AttributeBuilder[Any]("label")
  lazy val lang = new AttributeBuilder[Any]("lang")
  lazy val loop = new AttributeBuilder[Any]("loop")
  lazy val open = new BoolAttributeBuilder("open")
  lazy val optimum = new AttributeBuilder[Double]("open")
  lazy val placeholder = new AttributeBuilder[String]("placeholder")
  lazy val pattern = new AttributeBuilder[Any]("pattern")
  lazy val poster = new AttributeBuilder[Any]("poster")
  lazy val preload = new AttributeBuilder[Any]("preload")
  lazy val radiogroup = new AttributeBuilder[Any]("radiogroup")
  lazy val readonly = BoolAttributeBuilder("readonly")
  lazy val rel = new AttributeBuilder[Any]("rel")
  lazy val required = BoolAttributeBuilder("required")
  lazy val reversed = new AttributeBuilder[Any]("reversed")
  lazy val scope = new AttributeBuilder[Any]("scope")
  lazy val shape = new AttributeBuilder[Any]("shape")
  lazy val size = new AttributeBuilder[Int]("size")
  lazy val selected = BoolAttributeBuilder("selected")
  lazy val sizes = new AttributeBuilder[Any]("sizes")
  lazy val step = new AttributeBuilder[Double]("step")
  lazy val spellCheck = new AttributeBuilder[Any]("spellcheck")
  lazy val start = new AttributeBuilder[Int]("start")
  lazy val summary = new AttributeBuilder[Any]("summary")
  lazy val target = new AttributeBuilder[Any]("target")
  lazy val tabindex = new AttributeBuilder[Int]("tabindex")
  lazy val title = new AttributeBuilder[Any]("title")
  lazy val usemap = new AttributeBuilder[Any]("usemap")
  lazy val wrap = new AttributeBuilder[Any]("wrap")
  lazy val `type` = new AttributeBuilder[Any]("type")
  lazy val role = new AttributeBuilder[String]("role")
  lazy val tpe = `type`
  lazy val inputType = `type`
  lazy val className = new AttributeBuilder[String]("class")
  lazy val `class` = className
  lazy val cls = className
  lazy val forLabel = new AttributeBuilder[Any]("for")
  lazy val `for` = forLabel

  lazy val click = new MouseEventEmitterBuilder("click")
  lazy val resize = new MouseEventEmitterBuilder("resize")
  lazy val mousedown = new MouseEventEmitterBuilder("mousedown")
  lazy val mouseover = new MouseEventEmitterBuilder("mouseover")
  lazy val mouseenter = new MouseEventEmitterBuilder("mouseenter")
  lazy val mousemove = new MouseEventEmitterBuilder("mousemove")
  lazy val mouseleave = new MouseEventEmitterBuilder("mouseleave")
  lazy val contextMenu = new MouseEventEmitterBuilder("contextmenu")
  lazy val wheel = new MouseEventEmitterBuilder("wheel")
  lazy val select = new MouseEventEmitterBuilder("select")
  lazy val pointerLockChange = new MouseEventEmitterBuilder("pointerlockchange")
  lazy val pointerLockError = new MouseEventEmitterBuilder("pointerlockerror")
  lazy val drag = new DragEventEmitterBuilder("drag")
  lazy val dragStart = new DragEventEmitterBuilder("dragstart")
  lazy val dragEnd = new DragEventEmitterBuilder("dragend")
  lazy val dragEnter = new DragEventEmitterBuilder("dragenter")
  lazy val dragOver = new DragEventEmitterBuilder("dragover")
  lazy val dragLeave = new DragEventEmitterBuilder("dragleave")
  lazy val drop = new DragEventEmitterBuilder("drop")
  lazy val online = new EventEmitterBuilder("online")
  lazy val offline = new EventEmitterBuilder("offline")
  lazy val reset = new EventEmitterBuilder("reset")
  lazy val submit = new EventEmitterBuilder("submit")
  lazy val input = new InputEventEmitterBuilder("input")
  lazy val change = new InputEventEmitterBuilder("change")
  lazy val blur = new InputEventEmitterBuilder("blur")
  lazy val keydown = new KeyEventEmitterBuilder("keydown")
  lazy val keyup = new KeyEventEmitterBuilder("keyup")
  lazy val keypress = new KeyEventEmitterBuilder("keypress")
  lazy val cut = new ClipboardEventEmitterBuilder("cut")
  lazy val copy = new ClipboardEventEmitterBuilder("copy")
  lazy val paste = new ClipboardEventEmitterBuilder("paste")
  lazy val inputString = new StringEventEmitterBuilder("input")
  lazy val inputNumber = new NumberEventEmitterBuilder("input")
  @deprecated("Deprecated, use 'inputChecked' instead")
  lazy val inputBool = new BoolEventEmitterBuilder("change")
  lazy val inputChecked = new BoolEventEmitterBuilder("change")

  lazy val update = UpdateHookBuilder
  lazy val insert = InsertHookBuilder
  lazy val destroy = DestroyHookBuilder

  lazy val child = ChildStreamReceiverBuilder

  lazy val children = ChildrenStreamReceiverBuilder

  def createInputHandler() = createHandler[InputEvent]()
  def createMouseHandler() = createHandler[MouseEvent]()
  def createKeyboardHandler() = createHandler[KeyboardEvent]()
  def createDragHandler() = createHandler[DragEvent]()
  def createClipboardHandler() = createHandler[ClipboardEvent]()
  def createStringHandler(defaultValues: String*) = createHandler[String](defaultValues: _*)
  def createBoolHandler(defaultValues: Boolean*) = createHandler[Boolean](defaultValues: _*)
  def createNumberHandler(defaultValues: Double*) = createHandler[Double](defaultValues: _*)



  def createHandler[T](defaultValues: T*): Observable[T] with Sink[T] = {
    Sink.createHandler[T](defaultValues: _*)
  }




}
