package outwatch.dom

import outwatch.dom.helpers.DomUtils

/**
  * Trait that contains all tags, so they can be mixed in to other objects if needed.
  */
trait Tags {
  private def tag: (String) => (Seq[VDomModifier]) => VNode = DomUtils.hyperscriptHelper

  def a          (args: VDomModifier*): VNode = tag("a")(args)
  def abbr       (args: VDomModifier*): VNode = tag("abbr")(args)
  def address    (args: VDomModifier*): VNode = tag("address")(args)
  def area       (args: VDomModifier*): VNode = tag("area")(args)
  def article    (args: VDomModifier*): VNode = tag("article")(args)
  def aside      (args: VDomModifier*): VNode = tag("aside")(args)
  def audio      (args: VDomModifier*): VNode = tag("audio")(args)
  def b          (args: VDomModifier*): VNode = tag("b")(args)
  def base       (args: VDomModifier*): VNode = tag("base")(args)
  def bdi        (args: VDomModifier*): VNode = tag("bdi")(args)
  def bdo        (args: VDomModifier*): VNode = tag("bdo")(args)
  def blockquote (args: VDomModifier*): VNode = tag("blockquote")(args)
  def br         (args: VDomModifier*): VNode = tag("br")(args)
  def button     (args: VDomModifier*): VNode = tag("button")(args)
  def canvas     (args: VDomModifier*): VNode = tag("canvas")(args)
  def caption    (args: VDomModifier*): VNode = tag("caption")(args)
  def cite       (args: VDomModifier*): VNode = tag("cite")(args)
  def code       (args: VDomModifier*): VNode = tag("code")(args)
  def col        (args: VDomModifier*): VNode = tag("col")(args)
  def colgroup   (args: VDomModifier*): VNode = tag("colgroup")(args)
  def datalist   (args: VDomModifier*): VNode = tag("datalist")(args)
  def dd         (args: VDomModifier*): VNode = tag("dd")(args)
  def del        (args: VDomModifier*): VNode = tag("del")(args)
  def details    (args: VDomModifier*): VNode = tag("details")(args)
  def dfn        (args: VDomModifier*): VNode = tag("dfn")(args)
  def dialog     (args: VDomModifier*): VNode = tag("dialog")(args)
  def div        (args: VDomModifier*): VNode = tag("div")(args)
  def dl         (args: VDomModifier*): VNode = tag("dl")(args)
  def dt         (args: VDomModifier*): VNode = tag("dt")(args)
  def em         (args: VDomModifier*): VNode = tag("em")(args)
  def embed      (args: VDomModifier*): VNode = tag("embed")(args)
  def fieldset   (args: VDomModifier*): VNode = tag("fieldset")(args)
  def figcaption (args: VDomModifier*): VNode = tag("figcaption")(args)
  def figure     (args: VDomModifier*): VNode = tag("figure")(args)
  def footer     (args: VDomModifier*): VNode = tag("footer")(args)
  def form       (args: VDomModifier*): VNode = tag("form")(args)
  def h1         (args: VDomModifier*): VNode = tag("h1")(args)
  def h2         (args: VDomModifier*): VNode = tag("h2")(args)
  def h3         (args: VDomModifier*): VNode = tag("h3")(args)
  def h4         (args: VDomModifier*): VNode = tag("h4")(args)
  def h5         (args: VDomModifier*): VNode = tag("h5")(args)
  def h6         (args: VDomModifier*): VNode = tag("h6")(args)
  def header     (args: VDomModifier*): VNode = tag("header")(args)
  def hr         (args: VDomModifier*): VNode = tag("hr")(args)
  def i          (args: VDomModifier*): VNode = tag("i")(args)
  def iframe     (args: VDomModifier*): VNode = tag("iframe")(args)
  def img        (args: VDomModifier*): VNode = tag("img")(args)
  def input      (args: VDomModifier*): VNode = tag("input")(args)
  def ins        (args: VDomModifier*): VNode = tag("ins")(args)
  def keygen     (args: VDomModifier*): VNode = tag("keygen")(args)
  def label      (args: VDomModifier*): VNode = tag("label")(args)
  def legend     (args: VDomModifier*): VNode = tag("legend")(args)
  def li         (args: VDomModifier*): VNode = tag("li")(args)
  def main       (args: VDomModifier*): VNode = tag("main")(args)
  def mark       (args: VDomModifier*): VNode = tag("mark")(args)
  def menu       (args: VDomModifier*): VNode = tag("menu")(args)
  def menuitem   (args: VDomModifier*): VNode = tag("menuitem")(args)
  def meter      (args: VDomModifier*): VNode = tag("meter")(args)
  def nav        (args: VDomModifier*): VNode = tag("nav")(args)
  def ol         (args: VDomModifier*): VNode = tag("ol")(args)
  def optgroup   (args: VDomModifier*): VNode = tag("optgroup")(args)
  def option     (args: VDomModifier*): VNode = tag("option")(args)
  def output     (args: VDomModifier*): VNode = tag("output")(args)
  def p          (args: VDomModifier*): VNode = tag("p")(args)
  def param      (args: VDomModifier*): VNode = tag("param")(args)
  def pre        (args: VDomModifier*): VNode = tag("pre")(args)
  def progress   (args: VDomModifier*): VNode = tag("progress")(args)
  def section    (args: VDomModifier*): VNode = tag("section")(args)
  def select     (args: VDomModifier*): VNode = tag("select")(args)
  def small      (args: VDomModifier*): VNode = tag("small")(args)
  def span       (args: VDomModifier*): VNode = tag("span")(args)
  def strong     (args: VDomModifier*): VNode = tag("strong")(args)
  def sub        (args: VDomModifier*): VNode = tag("sub")(args)
  def summary    (args: VDomModifier*): VNode = tag("summary")(args)
  def sup        (args: VDomModifier*): VNode = tag("sup")(args)
  def table      (args: VDomModifier*): VNode = tag("table")(args)
  def tbody      (args: VDomModifier*): VNode = tag("tbody")(args)
  def td         (args: VDomModifier*): VNode = tag("td")(args)
  def textarea   (args: VDomModifier*): VNode = tag("textarea")(args)
  def tfoot      (args: VDomModifier*): VNode = tag("tfoot")(args)
  def th         (args: VDomModifier*): VNode = tag("th")(args)
  def thead      (args: VDomModifier*): VNode = tag("thead")(args)
  def time       (args: VDomModifier*): VNode = tag("time")(args)
  def tr         (args: VDomModifier*): VNode = tag("tr")(args)
  def track      (args: VDomModifier*): VNode = tag("track")(args)
  def ul         (args: VDomModifier*): VNode = tag("ul")(args)
  def video      (args: VDomModifier*): VNode = tag("video")(args)
  def wbr        (args: VDomModifier*): VNode = tag("wbr")(args)
}
